version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:

  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-deps-{{ checksum "pom.xml" }}
      - run:
          name: Build with Maven
          command: mvn clean package
      - save_cache:
          paths:
            - ~/.m2
          key: maven-deps-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - target/*.war
            - Dockerfile

  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-deps-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn test

  build_and_push_image:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - docker/check
      - docker/build:
          image: bodeomoboya01/java-hello-world-01
          tag: ${SHA256:elHZTLUDGZ0sUUnwPpdYGrzhbNkBqE5FWJ6IYDNUVrM}
      - docker/push:
          image: bodeomoboya01/java-hello-world-01
          tag: ${SHA256:elHZTLUDGZ0sUUnwPpdYGrzhbNkBqE5FWJ6IYDNUVrM}

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - build_and_push_image:
          requires:
            - test
          filters:
            branches:
              only: develop